# Generated by Django 5.2.4 on 2025-08-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='prompt',
            field=models.TextField(default=True, null=True),
        ),
    ]
