# Generated by Django 5.2.4 on 2025-08-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_userstats_last_mood_update_alter_journal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
