# Generated by Django 5.2.4 on 2025-08-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_userstats_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='awarded_xp',
            field=models.BooleanField(default=False),
        ),
    ]
