# Generated by Django 5.2.4 on 2025-08-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_moodlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('missed', 'Missed'), ('pending', 'Pending')], default='new', max_length=20),
        ),
    ]
