# Generated by Django 5.2.4 on 2025-08-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_habit_last_checkin_alter_habit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='last_mood_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
