# Generated by Django 5.2.4 on 2025-08-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_habit_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('missed', 'Missed'), ('pending', 'Pending'), ('grace_period', 'Grace Period')], default='new', max_length=20),
        ),
    ]
