# Generated by Django 5.2.4 on 2025-08-10 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_habit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='dashboard.habit')),
            ],
            options={
                'unique_together': {('habit', 'date')},
            },
        ),
    ]
