# Generated by Django 5.2.4 on 2025-08-10 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_habitcheckinlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('text', models.TextField()),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='dashboard.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_reflections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'habit', 'date')},
            },
        ),
    ]
