# Generated by Django 5.2.4 on 2025-08-11 03:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_habitreflection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habitreflection',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='habit',
            name='schedule_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('custom', 'Custom')], default='daily', max_length=10),
        ),
        migrations.AddField(
            model_name='habit',
            name='scheduled_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='habit',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('missed', 'Missed'), ('pending', 'Pending'), ('grace_period', 'Grace Period'), ('inactive', 'Inactive')], default='new', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='habitreflection',
            constraint=models.UniqueConstraint(fields=('user', 'habit', 'date'), name='imp_details'),
        ),
    ]
